In [1]:
# reading the basic libraries
import pandas as pd
import numpy as np

In [15]:
# creating the coloumns list
col_names = ["col1", "col2", "col3","col4","col5","col6", "col7", "col8","col9","col10","col11", "col12", "col13","col14","col15","col16", "col17", "col18","col19","col20","col21","col22", "col23", "col24","col25","col26","col27","col28", "col29", "col30"]
dataset = pd.read_csv('groceries.csv', names=col_names)
dataset

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,whipped/sour cream,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9831,cooking chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9832,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,cling film/bags,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9833,semi-finished bread,bottled water,soda,bottled beer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9834,chicken,tropical fruit,other vegetables,vinegar,shopping bags,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# replacing the NAN values with space
dataset = df.replace(np.nan, '', regex=True)
dataset

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,...,col21,col22,col23,col24,col25,col26,col27,col28,col29,col30
0,citrus fruit,semi-finished bread,margarine,ready soups,,,,,,,...,,,,,,,,,,
1,tropical fruit,yogurt,coffee,,,,,,,,...,,,,,,,,,,
2,whole milk,,,,,,,,,,...,,,,,,,,,,
3,pip fruit,yogurt,cream cheese,meat spreads,,,,,,,...,,,,,,,,,,
4,other vegetables,whole milk,condensed milk,long life bakery product,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,whipped/sour cream,...,,,,,,,,,,
9831,cooking chocolate,,,,,,,,,,...,,,,,,,,,,
9832,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,cling film/bags,...,,,,,,,,,,
9833,semi-finished bread,bottled water,soda,bottled beer,,,,,,,...,,,,,,,,,,
9834,chicken,tropical fruit,other vegetables,vinegar,shopping bags,,,,,,...,,,,,,,,,,

In [9]:
dataset
transactions = []
for i in range(0, 9835):
    transactions.append([str(dataset.values[i,u]) for u in range(1, 30)])

In [10]:
groceries_series  = pd.DataFrame(pd.Series(transactions))
groceries_series 
groceries_series.columns = ["business"]
groceries_series

                                               business
0     [semi-finished bread, margarine, ready soups, ...
1     [yogurt, coffee, , , , , , , , , , , , , , , ,...
2     [, , , , , , , , , , , , , , , , , , , , , , ,...
3     [yogurt, cream cheese , meat spreads, , , , , ...
4     [whole milk, condensed milk, long life bakery ...
...                                                 ...
9830  [chicken, beef, hamburger meat, citrus fruit, ...
9831  [, , , , , , , , , , , , , , , , , , , , , , ,...
9832  [citrus fruit, other vegetables, butter, yogur...
9833  [bottled water, soda, bottled beer, , , , , , ...
9834  [tropical fruit, other vegetables, vinegar, sh...

[9835 rows x 1 columns]

In [11]:
# replacing commas with zero's
X = groceries_series['business'].str.join(sep=',').str.get_dummies(sep=',')
X

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
9831,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9832,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9833,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9834,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [12]:
# getting maximum of 3 itemsets
from mlxtend.frequent_patterns import apriori,association_rules
frequent_itemsets = apriori(X, min_support=0.005, max_len=3,use_colnames = True)
frequent_itemsets

      support                                          itemsets
0    0.007422                           (Instant food products)
1    0.026335                                        (UHT-milk)
2    0.016675                                   (baking powder)
3    0.021556                                            (beef)
4    0.020946                                         (berries)
..        ...                                               ...
630  0.005389                 (whole milk, soda, shopping bags)
631  0.008948                        (soda, whole milk, yogurt)
632  0.005999  (whole milk, whipped/sour cream, tropical fruit)
633  0.010473              (tropical fruit, whole milk, yogurt)
634  0.009964          (whipped/sour cream, whole milk, yogurt)

[635 rows x 2 columns]

In [13]:
frequent_itemsets.sort_values('support',ascending = False,inplace=True)
frequent_itemsets.sort_values

<bound method DataFrame.sort_values of       support                                          itemsets
110  0.182613                                      (whole milk)
83   0.149771                                      (rolls/buns)
68   0.146721                                (other vegetables)
93   0.144484                                            (soda)
111  0.116624                                          (yogurt)
..        ...                                               ...
347  0.005084                 (hygiene articles, shopping bags)
551  0.005084         (other vegetables, domestic eggs, yogurt)
87   0.005084                                          (sauces)
283  0.005084                (frozen vegetables, domestic eggs)
557  0.005084  (frozen vegetables, root vegetables, whole milk)

[635 rows x 2 columns]>

In [14]:
# obtaining the antecedent and consequents
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head(20)
rules.sort_values('lift',ascending = False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
618,(tropical fruit),"(pip fruit, other vegetables)",0.055923,0.020437,0.007829,0.140000,6.850249,0.006686,1.139026
615,"(pip fruit, other vegetables)",(tropical fruit),0.020437,0.055923,0.007829,0.383085,6.850249,0.006686,1.530319
617,(pip fruit),"(tropical fruit, other vegetables)",0.047483,0.024403,0.007829,0.164882,6.756736,0.006670,1.168215
616,"(tropical fruit, other vegetables)",(pip fruit),0.024403,0.047483,0.007829,0.320833,6.756736,0.006670,1.402478
866,(root vegetables),"(citrus fruit, other vegetables)",0.079715,0.015353,0.006812,0.085459,5.566166,0.005589,1.076657
863,"(citrus fruit, other vegetables)",(root vegetables),0.015353,0.079715,0.006812,0.443709,5.566166,0.005589,1.654321
178,(pip fruit),(tropical fruit),0.047483,0.055923,0.013625,0.286938,5.130971,0.010969,1.323976
179,(tropical fruit),(pip fruit),0.055923,0.047483,0.013625,0.243636,5.130971,0.010969,1.259337
1499,"(fruit/vegetable juice, other vegetables)",(tropical fruit),0.017895,0.055923,0.005084,0.284091,5.080062,0.004083,1.318711
1502,(tropical fruit),"(fruit/vegetable juice, other vegetables)",0.055923,0.017895,0.005084,0.090909,5.080062,0.004083,1.080315