In [60]:
# importing the basic libraries
import pandas as pd
import numpy as np

In [61]:
# reading the file
dataset=pd.read_csv('my_movies.csv')
dataset

,V1,V2,V3,V4,V5,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile
0,Sixth Sense,LOTR1,Harry Potter1,Green Mile,LOTR2,1,0,1,1,0,1,0,0,0,1
1,Gladiator,Patriot,Braveheart,NaN,NaN,0,1,0,0,1,0,0,0,1,0
2,LOTR1,LOTR2,NaN,NaN,NaN,0,0,1,0,0,1,0,0,0,0
3,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
4,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
5,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
6,Harry Potter1,Harry Potter2,NaN,NaN,NaN,0,0,0,1,0,0,1,0,0,0
7,Gladiator,Patriot,NaN,NaN,NaN,0,1,0,0,1,0,0,0,0,0
8,Gladiator,Patriot,Sixth Sense,NaN,NaN,1,1,0,0,1,0,0,0,0,0
9,Sixth Sense,LOTR,Gladiator,Green Mile,NaN,1,1,0,0,0,0,0,1,0,1

In [62]:
# dropping the unwanted columns
dataset.drop(['V1','V2','V3','V4','V5'],inplace=True,axis=1)
dataset

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile
0,1,0,1,1,0,1,0,0,0,1
1,0,1,0,0,1,0,0,0,1,0
2,0,0,1,0,0,1,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0
4,1,1,0,0,1,0,0,0,0,0
5,1,1,0,0,1,0,0,0,0,0
6,0,0,0,1,0,0,1,0,0,0
7,0,1,0,0,1,0,0,0,0,0
8,1,1,0,0,1,0,0,0,0,0
9,1,1,0,0,0,0,0,1,0,1

In [63]:
# installing mlxtend
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\dell\anaconda3\lib\site-packages (0.18.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\dell\anaconda3\lib\site-packages (from mlxtend) (1.5.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\dell\anaconda3\lib\site-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\dell\anaconda3\lib\site-packages (from mlxtend) (0.23.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\dell\anaconda3\lib\site-packages (from mlxtend) (1.18.5)
Requirement already satisfied: joblib>=0.13.2 in c:\users\dell\anaconda3\lib\site-packages (from mlxtend) (0.16.0)
Requirement already satisfied: pandas>=0.24.2 in c:\users\dell\anaconda3\lib\site-packages (from mlxtend) (1.0.5)
Requirement already satisfied: setuptools in c:\users\dell\anaconda3\lib\site-packages (from mlxtend) (49.2.0.post20200714)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)

In [67]:
from mlxtend.frequent_patterns import apriori,association_rules
frequent_itemsets = apriori(dataset, min_support=0.005, max_len=5,use_colnames = True)
frequent_itemsets

    support                                           itemsets
0       0.6                                      (Sixth Sense)
1       0.7                                        (Gladiator)
2       0.2                                            (LOTR1)
3       0.2                                    (Harry Potter1)
4       0.6                                          (Patriot)
5       0.2                                            (LOTR2)
6       0.1                                    (Harry Potter2)
7       0.1                                             (LOTR)
8       0.1                                       (Braveheart)
9       0.2                                       (Green Mile)
10      0.5                           (Gladiator, Sixth Sense)
11      0.1                               (LOTR1, Sixth Sense)
12      0.1                       (Harry Potter1, Sixth Sense)
13      0.4                             (Patriot, Sixth Sense)
14      0.1                               (LOTR2, Sixth Sense)
15      0.1                                (LOTR, Sixth Sense)
16      0.2                          (Green Mile, Sixth Sense)
17      0.6                               (Gladiator, Patriot)
18      0.1                                  (Gladiator, LOTR)
19      0.1                            (Gladiator, Braveheart)
20      0.1                            (Gladiator, Green Mile)
21      0.1                             (Harry Potter1, LOTR1)
22      0.2                                     (LOTR2, LOTR1)
23      0.1                                (Green Mile, LOTR1)
24      0.1                             (Harry Potter1, LOTR2)
25      0.1                     (Harry Potter1, Harry Potter2)
26      0.1                        (Harry Potter1, Green Mile)
27      0.1                              (Patriot, Braveheart)
28      0.1                                (Green Mile, LOTR2)
29      0.1                                 (LOTR, Green Mile)
30      0.4                  (Gladiator, Patriot, Sixth Sense)
31      0.1                     (Gladiator, LOTR, Sixth Sense)
32      0.1               (Gladiator, Green Mile, Sixth Sense)
33      0.1                (Harry Potter1, LOTR1, Sixth Sense)
34      0.1                        (LOTR2, LOTR1, Sixth Sense)
35      0.1                   (Green Mile, LOTR1, Sixth Sense)
36      0.1                (Harry Potter1, LOTR2, Sixth Sense)
37      0.1           (Harry Potter1, Green Mile, Sixth Sense)
38      0.1                   (Green Mile, LOTR2, Sixth Sense)
39      0.1                    (LOTR, Green Mile, Sixth Sense)
40      0.1                   (Gladiator, Patriot, Braveheart)
41      0.1                      (Gladiator, LOTR, Green Mile)
42      0.1                      (Harry Potter1, LOTR2, LOTR1)
43      0.1                 (Harry Potter1, Green Mile, LOTR1)
44      0.1                         (Green Mile, LOTR2, LOTR1)
45      0.1                 (Harry Potter1, Green Mile, LOTR2)
46      0.1         (Gladiator, LOTR, Green Mile, Sixth Sense)
47      0.1         (Harry Potter1, LOTR2, LOTR1, Sixth Sense)
48      0.1    (Harry Potter1, Green Mile, LOTR1, Sixth Sense)
49      0.1            (Green Mile, LOTR2, LOTR1, Sixth Sense)
50      0.1    (Harry Potter1, Green Mile, LOTR2, Sixth Sense)
51      0.1          (Harry Potter1, Green Mile, LOTR2, LOTR1)
52      0.1  (Green Mile, LOTR2, LOTR1, Harry Potter1, Sixt...

In [68]:
frequent_itemsets.sort_values('support',ascending = False,inplace=True)
frequent_itemsets.sort_values

<bound method DataFrame.sort_values of     support                                           itemsets
1       0.7                                        (Gladiator)
0       0.6                                      (Sixth Sense)
4       0.6                                          (Patriot)
17      0.6                               (Gladiator, Patriot)
10      0.5                           (Gladiator, Sixth Sense)
30      0.4                  (Gladiator, Patriot, Sixth Sense)
13      0.4                             (Patriot, Sixth Sense)
9       0.2                                       (Green Mile)
22      0.2                                     (LOTR2, LOTR1)
16      0.2                          (Green Mile, Sixth Sense)
2       0.2                                            (LOTR1)
3       0.2                                    (Harry Potter1)
5       0.2                                            (LOTR2)
49      0.1            (Green Mile, LOTR2, LOTR1, Sixth Sense)
48      0.1    (Harry Potter1, Green Mile, LOTR1, Sixth Sense)
35      0.1                   (Green Mile, LOTR1, Sixth Sense)
36      0.1                (Harry Potter1, LOTR2, Sixth Sense)
37      0.1           (Harry Potter1, Green Mile, Sixth Sense)
38      0.1                   (Green Mile, LOTR2, Sixth Sense)
39      0.1                    (LOTR, Green Mile, Sixth Sense)
40      0.1                   (Gladiator, Patriot, Braveheart)
41      0.1                      (Gladiator, LOTR, Green Mile)
42      0.1                      (Harry Potter1, LOTR2, LOTR1)
43      0.1                 (Harry Potter1, Green Mile, LOTR1)
44      0.1                         (Green Mile, LOTR2, LOTR1)
51      0.1          (Harry Potter1, Green Mile, LOTR2, LOTR1)
33      0.1                (Harry Potter1, LOTR1, Sixth Sense)
45      0.1                 (Harry Potter1, Green Mile, LOTR2)
46      0.1         (Gladiator, LOTR, Green Mile, Sixth Sense)
50      0.1    (Harry Potter1, Green Mile, LOTR2, Sixth Sense)
47      0.1         (Harry Potter1, LOTR2, LOTR1, Sixth Sense)
34      0.1                        (LOTR2, LOTR1, Sixth Sense)
26      0.1                        (Harry Potter1, Green Mile)
32      0.1               (Gladiator, Green Mile, Sixth Sense)
31      0.1                     (Gladiator, LOTR, Sixth Sense)
6       0.1                                    (Harry Potter2)
7       0.1                                             (LOTR)
8       0.1                                       (Braveheart)
11      0.1                               (LOTR1, Sixth Sense)
12      0.1                       (Harry Potter1, Sixth Sense)
14      0.1                               (LOTR2, Sixth Sense)
15      0.1                                (LOTR, Sixth Sense)
18      0.1                                  (Gladiator, LOTR)
19      0.1                            (Gladiator, Braveheart)
20      0.1                            (Gladiator, Green Mile)
21      0.1                             (Harry Potter1, LOTR1)
23      0.1                                (Green Mile, LOTR1)
24      0.1                             (Harry Potter1, LOTR2)
25      0.1                     (Harry Potter1, Harry Potter2)
27      0.1                              (Patriot, Braveheart)
28      0.1                                (Green Mile, LOTR2)
29      0.1                                 (LOTR, Green Mile)
52      0.1  (Green Mile, LOTR2, LOTR1, Harry Potter1, Sixt...>

In [69]:
# obtaining the antecedents and consequents
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.sort_values('lift',ascending = False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
110,"(Harry Potter1, LOTR1)","(Green Mile, LOTR2)",0.1,0.1,0.1,1.0,10.0,0.09,inf
162,"(Harry Potter1, LOTR2)","(LOTR1, Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
84,(LOTR),"(Gladiator, Green Mile)",0.1,0.1,0.1,1.0,10.0,0.09,inf
109,"(Harry Potter1, LOTR2)","(Green Mile, LOTR1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
223,"(Green Mile, LOTR2)","(Harry Potter1, LOTR1, Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
222,"(Harry Potter1, LOTR1, Sixth Sense)","(Green Mile, LOTR2)",0.1,0.1,0.1,1.0,10.0,0.09,inf
81,"(Gladiator, Green Mile)",(LOTR),0.1,0.1,0.1,1.0,10.0,0.09,inf
135,"(Gladiator, Green Mile)","(LOTR, Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf
111,"(Green Mile, LOTR2)","(Harry Potter1, LOTR1)",0.1,0.1,0.1,1.0,10.0,0.09,inf
34,"(Harry Potter1, Green Mile)","(LOTR1, Sixth Sense)",0.1,0.1,0.1,1.0,10.0,0.09,inf