In [120]:
# importing all the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing 
from sklearn.tree import DecisionTreeRegressor

In [121]:
# importing the dataset

fraud = pd.read_csv('Fraud_check.csv')   
fraud

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban
0,NO,Single,68833,50047,10,YES
1,YES,Divorced,33700,134075,18,YES
2,NO,Married,36925,160205,30,YES
3,YES,Single,50190,193264,15,YES
4,NO,Married,81002,27533,28,NO
5,NO,Divorced,33329,116382,0,NO
6,NO,Divorced,83357,80890,8,YES
7,YES,Single,62774,131253,3,YES
8,NO,Single,83519,102481,12,YES
9,YES,Divorced,98152,155482,4,YES
10,NO,Single,29732,102602,19,YES
11,NO,Single,61063,94875,6,YES
12,NO,Divorced,11794,148033,14,YES
13,NO,Married,61830,86649,16,YES
14,NO,Married,64070,57529,13,YES
15,NO,Divorced,69869,107764,29,NO
16,YES,Divorced,24987,34551,29,NO
17,YES,Married,39476,57194,25,NO
18,YES,Divorced,97957,59269,6,NO
19,NO,Single,10987,126953,30,YES
20,YES,Single,88636,147222,26,NO
21,YES,Divorced,14310,29106,7,YES
22,YES,Divorced,78969,155342,14,NO
23,NO,Single,92040,50495,12,YES
24,NO,Divorced,38239,28495,30,NO
25,NO,Divorced,31417,124606,27,YES
26,YES,Divorced,55299,169128,15,NO
27,YES,Single,87778,28542,12,YES
28,YES,Single,10379,128766,5,YES
29,YES,Divorced,94033,41863,30,YES
30,YES,Divorced,73854,117788,0,YES
31,NO,Divorced,64007,147414,21,NO
32,YES,Married,97200,51911,23,NO
33,YES,Single,82071,157251,21,NO
34,YES,Divorced,12514,183767,1,YES
35,YES,Married,31336,41117,30,YES
36,YES,Married,10163,193995,5,YES
37,NO,Married,68513,66912,5,YES
38,NO,Single,14912,177575,3,NO
39,NO,Married,74010,54981,16,YES
40,NO,Single,50777,199697,26,YES
41,YES,Married,49436,91524,1,NO
42,NO,Single,96485,51666,12,NO
43,YES,Divorced,70339,50020,10,NO
44,YES,Divorced,33614,98880,22,NO
45,YES,Married,81079,183095,14,YES
46,YES,Married,31532,137346,27,YES
47,YES,Single,44034,34964,2,NO
48,NO,Married,16264,35480,12,NO
49,NO,Divorced,45706,160195,15,YES
50,YES,Single,79616,145804,3,YES
51,YES,Single,40137,174042,30,NO
52,NO,Single,97703,91828,23,NO
53,YES,Single,21917,139143,7,YES
54,NO,Divorced,81939,98207,23,NO
55,YES,Single,19925,89965,16,YES
56,NO,Married,34703,69832,25,YES
57,NO,Single,78573,70744,13,NO
58,YES,Single,10870,158047,15,NO
59,NO,Single,65065,102228,11,NO
60,YES,Married,94418,91138,23,NO
61,YES,Married,26972,86169,8,NO
62,NO,Divorced,91684,147684,13,YES
63,YES,Divorced,51685,95831,9,NO
64,YES,Single,62158,118261,15,NO
65,NO,Divorced,58312,194738,29,NO
66,YES,Married,42507,66985,12,YES
67,YES,Married,61486,173986,24,NO
68,NO,Single,10150,139642,5,NO
69,YES,Single,99619,86896,29,NO
70,YES,Divorced,89302,80904,3,YES
71,NO,Single,94287,105680,22,NO
72,YES,Divorced,41344,108300,27,YES
73,YES,Single,41382,174789,2,YES
74,NO,Divorced,32434,182319,17,NO
75,NO,Married,61105,50404,19,YES
76,YES,Married,67628,129164,11,NO
77,YES,Married,31458,118344,26,NO
78,YES,Divorced,73411,143153,0,NO
79,NO,Divorced,10329,140885,7,YES
80,NO,Married,44947,28184,26,NO
81,YES,Divorced,35610,121608,24,NO
82,NO,Divorced,66564,111068,26,YES
83,NO,Divorced,87348,73963,18,YES
84,NO,Married,69098,178083,4,YES
85,YES,Divorced,28449,125155,12,YES
86,YES,Divorced,39277,97520,29,YES
87,YES,Single,13747,64075,23,NO
88,NO,Married,86652,63896,24,YES
89,YES,Married,26741,176050,20,NO
90,NO,Divorced,77634,101232,29,NO
91,YES,Married,99325,73733,10,YES
92,NO,Divorced,85651,114621,13,NO
93,YES,Married,15296,137676,3,YES
94,NO,Single,10348,122705,6,YES
95,YES,Single,41395,121498,28,YES
96,NO,Single,22258,63622,17,NO
97,YES,Divorced,79583,37849,19,YES
98,YES,Married,22187,77053,18,YES
99,NO,Married,52495,114350,12,NO
100,YES,Single,93078,46444,25,NO
101,YES,Married,35072,50490,20,YES
102,YES,Divorced,32662,91488,23,NO
103,NO,Divorced,89250,76318,5,YES
104,NO,Single,41641,174423,14,NO
105,NO,Single,55873,46893,15,NO
106,YES,Single,19169,58535,20,YES
107,NO,Married,46629,52424,6,YES
108,YES,Married,51927,120894,10,YES
109,YES,Married,69224,178585,8,YES
110,NO,Single,24557,32450,19,YES
111,NO,Single,77762,164526,11,YES
112,YES,Single,96355,193038,26,YES
113,YES,Married,90910,100347,7,YES
114,NO,Single,21945,197934,7,NO
115,YES,Divorced,79357,78251,21,YES
116,NO,Married,42784,132570,12,NO
117,NO,Single,54638,96370,29,YES
118,NO,Divorced,29944,199174,10,NO
119,NO,Divorced,97318,47202,30,YES
120,YES,Single,52022,135886,11,YES
121,YES,Married,20391,86648,16,YES
122,YES,Married,21016,140762,26,NO
123,YES,Married,26679,79683,26,NO
124,YES,Divorced,70682,139324,13,NO
125,YES,Divorced,87326,155669,11,NO
126,YES,Divorced,15853,195022,3,YES
127,NO,Single,75501,93035,28,YES
128,NO,Married,97984,100897,27,YES
129,YES,Single,53378,65469,26,NO
130,YES,Single,93458,87730,7,YES
131,YES,Single,56501,174321,16,YES
132,NO,Divorced,46955,67820,12,NO
133,NO,Single,33492,86646,14,YES
134,YES,Married,35832,190365,28,NO
135,YES,Divorced,12470,75323,19,YES
136,NO,Divorced,53981,53513,9,NO
137,YES,Single,22773,115884,6,NO
138,NO,Single,84691,155335,25,NO
139,YES,Divorced,50087,86904,20,NO
140,YES,Married,27877,93390,4,YES
141,YES,Married,56647,194364,23,YES
142,NO,Single,59419,122654,26,YES
143,YES,Single,26783,154013,11,NO
144,YES,Single,79453,156503,29,YES
145,NO,Divorced,33962,197422,2,YES
146,NO,Divorced,84429,57931,28,YES
147,YES,Divorced,63057,163252,28,NO
148,NO,Married,43128,197038,21,NO
149,NO,Single,40220,49505,25,NO
150,NO,Married,79700,161759,28,NO
151,NO,Single,67083,109110,10,NO
152,NO,Single,22054,91889,16,NO
153,YES,Divorced,18192,114841,28,NO
154,NO,Single,25222,82520,29,YES
155,YES,Single,58635,139624,7,NO
156,YES,Married,39114,125987,3,YES
157,YES,Married,48738,115631,5,NO
158,NO,Divorced,28496,163347,11,NO
159,YES,Single,62209,28504,1,NO
160,YES,Divorced,87677,79972,0,YES
161,YES,Married,93659,185596,30,YES
162,YES,Married,56503,177468,21,YES
163,YES,Divorced,27081,91851,15,YES
164,YES,Single,48779,153192,28,NO
165,YES,Married,91304,38463,23,YES
166,NO,Married,49520,73466,22,YES
167,NO,Married,41117,194381,25,NO
168,NO,Divorced,18199,167629,30,NO
169,YES,Single,76992,76933,6,YES
170,NO,Divorced,98588,143402,10,NO
171,YES,Married,20719,103614,24,NO
172,NO,Married,13068,52819,23,YES
173,YES,Single,84835,105110,16,YES
174,YES,Single,44795,149857,8,NO
175,YES,Single,39052,57055,13,NO
176,NO,Married,38704,75169,28,NO
177,NO,Married,98416,31156,13,YES
178,NO,Single,86958,85832,15,YES
179,YES,Married,29222,192451,22,YES
180,YES,Single,71357,149101,19,NO
181,NO,Divorced,29543,36116,20,NO
182,NO,Divorced,23855,89632,4,YES
183,NO,Single,84836,39523,30,YES
184,NO,Divorced,93307,70138,15,YES
185,NO,Married,64614,92975,0,YES
186,NO,Married,72949,166976,19,YES
187,NO,Single,79211,59558,5,YES
188,NO,Divorced,28707,137569,10,NO
189,YES,Married,83229,189301,11,YES
190,NO,Single,73620,90459,19,NO
191,NO,Single,70819,176341,7,YES
192,YES,Married,48313,126556,10,YES
193,YES,Married,37481,198213,25,NO
194,YES,Single,20851,103981,28,NO
195,YES,Single,86079,181370,13,YES
196,YES,Married,10933,28410,21,NO
197,NO,Single,66905,98056,4,YES
198,NO,Single,36890,48025,28,YES
199,YES,Married,19060,145744,9,YES
200,YES,Single,61906,162777,17,YES
201,YES,Divorced,31088,58225,27,YES
202,YES,Single,70365,28661,0,YES
203,YES,Divorced,56536,117260,4,NO
204,NO,Married,16992,173091,14,NO
205,NO,Married,14300,131906,20,YES
206,YES,Single,51914,52227,16,YES
207,YES,Married,12083,138108,28,NO
208,YES,Single,71376,141502,3,NO
209,YES,Single,99307,186239,25,YES
210,YES,Single,35200,125993,13,YES
211,YES,Married,70812,57194,8,YES
212,YES,Divorced,62067,112659,14,NO
213,YES,Single,62365,107069,13,NO
214,NO,Divorced,80618,140159,16,NO
215,NO,Divorced,52891,28576,22,NO
216,NO,Divorced,31409,85128,22,NO
217,YES,Divorced,81790,179220,19,YES
218,NO,Married,57794,38091,19,NO
219,YES,Divorced,20604,26814,9,NO
220,YES,Divorced,83459,115168,30,NO
221,YES,Single,43051,134135,14,NO
222,YES,Divorced,68911,168248,27,NO
223,YES,Married,38374,192297,17,YES
224,NO,Married,86784,55717,25,YES
225,YES,Single,42488,125883,0,YES
226,NO,Single,35922,77719,28,NO
227,YES,Single,46610,182921,17,YES
228,NO,Married,28764,100696,9,YES
229,NO,Married,75170,35780,10,NO
230,NO,Married,24370,81593,14,YES
231,YES,Single,84083,153147,2,NO
232,YES,Married,11784,150349,2,NO
233,NO,Married,10003,63701,19,YES
234,NO,Single,98970,102498,14,NO
235,NO,Divorced,77735,87541,9,NO
236,YES,Married,46070,193193,3,NO
237,NO,Married,27143,128996,3,YES
238,YES,Single,56974,72968,9,YES
239,NO,Divorced,99109,76145,26,NO
240,NO,Single,32603,139146,30,YES
241,YES,Single,24215,31377,18,YES
242,NO,Divorced,33092,84368,2,YES
243,NO,Divorced,71297,181549,10,YES
244,YES,Single,68268,154647,27,NO
245,NO,Single,33810,183221,24,NO
246,YES,Single,49995,38139,25,NO
247,YES,Divorced,11865,108245,1,NO
248,NO,Single,28904,105374,17,YES
249,YES,Single,39144,35376,0,YES
250,NO,Married,31591,156973,16,NO
251,YES,Single,30167,173228,7,NO
252,NO,Single,72382,40855,28,YES
253,YES,Single,79869,77256,29,NO
254,NO,Divorced,70526,193263,26,NO
255,YES,Married,38143,170030,8,NO
256,YES,Married,70298,168568,14,NO
257,YES,Married,54747,31611,17,YES
258,NO,Divorced,92997,74119,28,YES
259,NO,Married,24347,197841,7,NO
260,YES,Single,57445,92333,28,NO
261,NO,Single,70645,68788,7,YES
262,NO,Divorced,69540,120415,21,NO
263,YES,Married,70712,69386,21,YES
264,NO,Single,32900,118899,5,NO
265,NO,Married,14326,101996,4,YES
266,YES,Married,43865,173276,17,YES
267,NO,Single,29046,183946,11,NO
268,NO,Single,95088,98378,3,YES
269,YES,Married,38586,125450,13,YES
270,NO,Married,30468,130680,5,NO
271,NO,Single,42254,183682,20,NO
272,NO,Single,32467,126488,1,YES
273,YES,Divorced,68404,58942,20,NO
274,YES,Married,58451,112584,25,NO
275,YES,Married,86208,55591,0,YES
276,NO,Single,62426,44251,17,YES
277,NO,Divorced,63710,117364,11,NO
278,NO,Married,25062,114823,11,NO
279,YES,Single,56438,74136,12,YES
280,NO,Divorced,17783,33184,1,NO
281,NO,Single,92426,167403,7,YES
282,YES,Married,64667,59590,29,NO
283,YES,Divorced,32483,129276,22,NO
284,NO,Divorced,15673,188383,22,YES
285,NO,Single,77511,63420,10,NO
286,YES,Divorced,76182,113724,6,NO
287,YES,Single,89831,77102,1,YES
288,YES,Married,12072,174196,21,YES
289,NO,Single,81231,196816,14,NO
290,YES,Married,48169,193003,30,YES
291,YES,Single,31699,62475,26,YES
292,YES,Single,15710,76406,1,YES
293,NO,Divorced,31645,43899,21,YES
294,YES,Single,98933,74074,2,NO
295,YES,Married,52912,40089,10,NO
296,YES,Divorced,68756,167600,26,NO
297,NO,Married,41087,36924,15,NO
298,NO,Single,46798,119904,21,YES
299,YES,Single,34475,197916,7,NO
300,NO,Married,98334,74052,30,NO
301,YES,Married,10900,39797,11,NO
302,YES,Divorced,61445,97109,27,NO
303,YES,Divorced,78796,189061,13,YES
304,YES,Divorced,62141,106757,23,YES
305,NO,Single,90945,161265,29,YES
306,YES,Divorced,88918,185099,12,NO
307,NO,Divorced,62873,31819,25,NO
308,YES,Married,70949,183445,30,NO
309,YES,Single,31521,123761,20,YES
310,YES,Divorced,59615,189435,22,YES
311,NO,Married,52111,50013,19,NO
312,YES,Single,34598,31641,18,NO
313,YES,Single,61124,124848,2,NO
314,NO,Single,59689,85255,4,NO
315,YES,Divorced,23075,176278,19,NO
316,NO,Married,48192,70323,25,NO
317,YES,Married,77367,116745,23,NO
318,NO,Divorced,82625,121324,14,YES
319,YES,Divorced,51802,153308,24,YES
320,YES,Single,78922,78897,11,YES
321,NO,Single,38670,84215,6,YES
322,NO,Divorced,48392,160932,24,YES
323,YES,Married,47425,165175,13,NO
324,YES,Single,73906,171288,15,NO
325,NO,Single,94013,25779,16,YES
326,YES,Divorced,27698,165001,19,YES
327,YES,Married,26793,162777,7,NO
328,NO,Divorced,67033,93414,12,YES
329,NO,Single,20109,39360,10,NO
330,NO,Married,95185,43176,29,NO
331,YES,Married,27684,60999,15,YES
332,YES,Divorced,98240,84132,1,NO
333,YES,Single,18032,44775,13,YES
334,NO,Single,46470,118274,13,YES
335,YES,Married,33301,140998,15,NO
336,NO,Married,62800,73146,5,NO
337,YES,Married,27520,73490,7,NO
338,YES,Divorced,26094,111264,23,NO
339,YES,Single,13571,110940,10,NO
340,YES,Married,36239,54437,21,YES
341,NO,Married,77082,83900,8,YES
342,YES,Married,71572,31097,7,YES
343,YES,Divorced,30495,161143,17,NO
344,NO,Married,49771,192313,5,YES
345,YES,Divorced,32905,118798,6,NO
346,NO,Single,21337,134635,30,YES
347,NO,Married,16082,80991,0,YES
348,YES,Single,43883,42269,2,NO
349,YES,Divorced,15491,72255,30,YES
350,NO,Married,48081,89949,25,NO
351,YES,Married,36317,114922,12,NO
352,NO,Divorced,15627,72115,16,YES
353,YES,Married,51028,141622,29,NO
354,YES,Married,14422,176891,27,YES
355,YES,Single,45525,56488,17,NO
356,NO,Married,23480,46480,27,NO
357,NO,Married,19184,84034,28,NO
358,YES,Single,80239,96432,24,YES
359,YES,Single,33215,157299,11,NO
360,YES,Single,65203,107937,5,YES
361,YES,Divorced,65190,62671,20,NO
362,YES,Divorced,16320,75552,17,YES
363,YES,Single,21696,52584,7,YES
364,YES,Married,56129,62943,17,NO
365,NO,Divorced,74971,134321,10,YES
366,YES,Married,33356,131469,30,NO
367,YES,Married,29607,95404,24,YES
368,YES,Divorced,95319,128428,14,NO
369,NO,Married,94413,89122,28,NO
370,NO,Divorced,78963,86119,5,YES
371,YES,Single,66865,75580,5,NO
372,YES,Married,40427,168473,9,NO
373,NO,Married,93733,175719,21,YES
374,YES,Divorced,63543,147614,9,YES
375,NO,Married,41184,130935,2,NO
376,NO,Divorced,96652,188067,26,NO
377,YES,Single,56555,103490,30,NO
378,YES,Divorced,36457,152471,6,NO
379,NO,Single,26101,112774,13,NO
380,YES,Married,36156,197699,2,NO
381,NO,Single,49958,61920,4,NO
382,YES,Divorced,68696,139269,29,NO
383,YES,Married,97453,148246,5,YES
384,YES,Married,68533,147346,25,NO
385,NO,Single,96438,140132,27,NO
386,NO,Single,50348,140642,27,YES
387,YES,Single,85016,56597,9,YES
388,YES,Divorced,73188,151636,4,YES
389,YES,Single,64225,183187,5,YES
390,YES,Single,64437,57324,17,NO
391,NO,Married,66330,29934,1,NO
392,YES,Divorced,26372,37776,15,NO
393,NO,Married,30714,68687,30,YES
394,NO,Divorced,84263,64990,21,YES
395,YES,Single,86531,183094,5,NO
396,YES,Single,93090,176330,21,NO
397,NO,Married,79373,91689,14,YES
398,NO,Married,17440,64070,2,YES
399,NO,Single,81536,74497,21,NO
400,YES,Married,62494,197421,16,NO
401,NO,Married,37580,73065,20,NO
402,YES,Divorced,60822,105376,11,NO
403,NO,Divorced,96032,130912,27,YES
404,YES,Divorced,91545,34334,21,YES
405,NO,Divorced,73313,140266,28,NO
406,NO,Married,54345,107688,2,NO
407,NO,Single,33138,52144,6,NO
408,YES,Divorced,33579,77059,22,NO
409,NO,Single,83094,163058,1,NO
410,NO,Divorced,90065,41152,27,NO
411,NO,Married,51913,46253,19,NO
412,YES,Single,81378,28446,11,NO
413,YES,Single,32236,112890,11,YES
414,NO,Divorced,97980,27300,1,YES
415,NO,Divorced,38626,131493,21,NO
416,NO,Single,64230,33982,30,NO
417,NO,Divorced,38183,76625,2,NO
418,YES,Divorced,89277,104183,18,NO
419,NO,Married,68269,138074,20,NO
420,NO,Divorced,58751,84473,2,NO
421,YES,Single,88720,135185,13,NO
422,NO,Divorced,99311,191983,14,YES
423,NO,Married,94528,80249,19,YES
424,YES,Married,72268,94199,0,YES
425,YES,Divorced,79593,121506,27,NO
426,YES,Divorced,94247,50373,25,YES
427,NO,Divorced,76700,99025,10,NO
428,YES,Married,12011,128266,24,YES
429,NO,Single,87935,153748,30,YES
430,YES,Married,98720,161215,8,NO
431,NO,Single,38638,168360,25,YES
432,NO,Married,37857,157217,11,YES
433,NO,Married,15532,129265,14,YES
434,YES,Single,22159,87188,19,YES
435,NO,Divorced,91547,111774,4,YES
436,NO,Divorced,98738,158057,4,YES
437,YES,Married,21966,117250,20,YES
438,NO,Single,14398,74697,14,NO
439,YES,Divorced,18572,48956,8,NO
440,NO,Single,77312,170407,13,YES
441,NO,Divorced,42074,70314,24,NO
442,YES,Single,82799,193775,27,NO
443,YES,Single,12659,189209,9,NO
444,YES,Single,19649,36956,14,NO
445,NO,Divorced,50119,128451,12,NO
446,NO,Single,18888,65708,28,NO
447,NO,Married,83061,166606,5,YES
448,YES,Single,39343,114597,28,YES
449,NO,Married,92007,27875,11,NO
450,YES,Divorced,78728,91936,8,YES
451,YES,Divorced,48640,108262,10,YES
452,NO,Single,92070,42620,10,NO
453,YES,Single,97341,41504,26,NO
454,NO,Married,97493,29602,15,YES
455,NO,Married,78400,65533,23,YES
456,NO,Single,52862,53788,23,YES
457,NO,Married,11804,36055,24,YES
458,YES,Single,10455,110892,18,YES
459,YES,Divorced,25766,125407,21,NO
460,NO,Divorced,58199,54701,10,YES
461,NO,Single,88613,163901,6,YES
462,NO,Divorced,16690,149327,17,NO
463,NO,Divorced,71164,40460,3,YES
464,NO,Married,48825,143349,16,YES
465,NO,Divorced,29236,116282,21,NO
466,NO,Married,59689,186013,16,NO
467,YES,Divorced,48940,106946,20,YES
468,YES,Divorced,64320,38814,18,YES
469,YES,Single,84845,65487,13,YES
470,YES,Married,52663,148686,26,NO
471,NO,Single,17957,192410,21,YES
472,NO,Married,69018,151963,11,YES
473,YES,Single,58496,147367,16,YES
474,YES,Divorced,99128,80729,0,NO
475,NO,Single,35868,36081,12,YES
476,NO,Single,79478,183057,7,YES
477,YES,Divorced,57402,158849,29,NO
478,NO,Divorced,73795,65242,6,NO
479,YES,Married,58403,68995,21,NO
480,NO,Divorced,85972,72252,26,YES
481,YES,Single,62998,120012,13,NO
482,NO,Single,32786,125771,12,NO
483,NO,Single,17962,100961,10,NO
484,YES,Married,59440,114646,28,YES
485,NO,Single,94772,52766,23,NO
486,YES,Single,80083,57230,29,YES
487,YES,Single,81026,83402,13,YES
488,YES,Single,86883,76718,10,YES
489,YES,Married,39444,148821,6,NO
490,NO,Married,35886,120996,24,NO
491,NO,Divorced,24541,82029,10,NO
492,YES,Single,54502,98123,18,YES
493,NO,Married,17183,103226,29,NO
494,NO,Single,39562,197045,13,YES
495,NO,Married,70157,59156,24,NO
496,YES,Divorced,72151,59382,5,YES
497,NO,Single,65170,100331,3,NO
498,YES,Single,67936,164924,24,YES
499,YES,Single,93339,48744,2,YES
500,YES,Single,57365,158780,11,YES
501,NO,Divorced,56628,55842,4,YES
502,NO,Married,83814,53240,1,YES
503,YES,Married,75324,81550,17,YES
504,NO,Divorced,46939,198571,19,YES
505,NO,Divorced,71428,74910,15,YES
506,NO,Single,23884,111105,8,YES
507,YES,Single,95145,101272,24,YES
508,NO,Single,46002,195357,19,NO
509,NO,Married,20309,65531,27,YES
510,YES,Married,72115,75436,14,YES
511,NO,Married,42769,153233,5,YES
512,YES,Single,91870,137948,22,YES
513,NO,Divorced,55308,140400,10,NO
514,NO,Divorced,60789,31380,6,NO
515,NO,Divorced,51363,87868,13,NO
516,YES,Single,99239,76337,18,YES
517,NO,Single,19272,195078,26,NO
518,YES,Single,44411,112591,26,YES
519,YES,Single,60915,162102,25,YES
520,NO,Divorced,98433,142426,8,YES
521,NO,Divorced,81867,51104,15,NO
522,NO,Divorced,43980,103343,10,NO
523,NO,Divorced,50286,42198,12,NO
524,YES,Married,29385,164391,27,NO
525,YES,Single,47565,75307,23,NO
526,NO,Divorced,26494,82565,12,NO
527,NO,Married,59243,180274,27,NO
528,NO,Married,91488,172612,10,NO
529,NO,Divorced,33116,83388,14,NO
530,YES,Divorced,93364,194421,17,YES
531,YES,Married,70743,124440,14,YES
532,YES,Divorced,34007,98662,16,NO
533,NO,Divorced,26128,54113,19,YES
534,YES,Married,33748,91567,13,YES
535,NO,Married,38896,189851,3,NO
536,NO,Single,40674,157025,14,NO
537,YES,Single,97111,100651,6,NO
538,NO,Married,54850,119976,12,NO
539,YES,Divorced,32948,57390,8,NO
540,YES,Single,12682,110308,22,NO
541,YES,Divorced,12453,191874,30,YES
542,YES,Married,34655,199778,27,NO
543,NO,Single,59351,130816,13,NO
544,NO,Single,29916,133877,21,YES
545,YES,Divorced,36532,109079,8,NO
546,NO,Married,94583,59091,6,NO
547,YES,Single,92819,42690,25,YES
548,YES,Divorced,76535,154393,9,YES
549,NO,Married,91220,74058,11,YES
550,NO,Married,71238,68160,2,YES
551,YES,Married,32356,123082,0,YES
552,NO,Single,89094,109191,5,YES
553,NO,Single,91462,26884,13,YES
554,NO,Divorced,75585,147788,27,NO
555,NO,Single,31629,53848,10,NO
556,NO,Single,42063,34242,12,NO
557,YES,Married,12810,157421,10,NO
558,NO,Divorced,85570,191139,12,YES
559,YES,Divorced,72026,180424,26,NO
560,NO,Divorced,90444,182562,24,NO
561,NO,Married,50403,36861,29,YES
562,YES,Divorced,78867,100064,12,NO
563,YES,Married,95920,116495,6,YES
564,YES,Married,41545,30098,11,YES
565,NO,Divorced,63912,31064,28,NO
566,NO,Married,92498,33460,28,NO
567,YES,Single,16316,129912,30,NO
568,NO,Single,68617,150036,22,YES
569,YES,Single,59860,38074,12,YES
570,NO,Single,55981,161629,29,YES
571,NO,Single,34833,95421,7,YES
572,YES,Married,39818,148068,13,NO
573,YES,Married,59227,116161,20,NO
574,YES,Divorced,44809,28768,29,YES
575,NO,Divorced,10735,95975,13,YES
576,YES,Married,50242,79653,15,YES
577,YES,Married,56166,52940,5,YES
578,NO,Divorced,42483,185339,6,NO
579,YES,Single,70572,125112,7,YES
580,YES,Divorced,31721,123335,1,YES
581,YES,Divorced,31085,57473,10,YES
582,YES,Married,84931,32907,12,YES
583,NO,Married,69036,28874,19,NO
584,NO,Divorced,42679,155684,4,YES

In [185]:
# assigning particular codes or numbers to terms married, single, divorced
label_encoder = preprocessing.LabelEncoder()
fraud['Marital.Status']= label_encoder.fit_transform(fraud['Marital.Status'])

In [186]:
fraud['Marital.Status'].unique()

array([2, 0, 1])

In [209]:
#replacing all 'yes' with '1' and 'no' with '0'
fraud = fraud.replace(to_replace = ['YES','NO'],value = ['1','0'])

In [190]:
# defining a new coloumn which represents Taxable.Income>30000 as 1 and Taxable.Income<=3000 as 0
# '1' represents 'good'
# '0' represents 'risky'
fraud['Taxable.Risky']=(fraud['Taxable.Income']>30000)*1

In [191]:
# defining the independent variable
x=fraud[['Undergrad','Marital.Status','City.Population','Work.Experience','Urban']]

In [192]:
# defining the target variable
y=fraud['Taxable.Risky']

In [210]:
fraud

,Undergrad,Marital.Status,Taxable.Income,City.Population,Work.Experience,Urban,Taxable.Risky
0,0,2,68833,50047,10,1,1
1,1,0,33700,134075,18,1,1
2,0,1,36925,160205,30,1,1
3,1,2,50190,193264,15,1,1
4,0,1,81002,27533,28,0,1
5,0,0,33329,116382,0,0,1
6,0,0,83357,80890,8,1,1
7,1,2,62774,131253,3,1,1
8,0,2,83519,102481,12,1,1
9,1,0,98152,155482,4,1,1
10,0,2,29732,102602,19,1,0
11,0,2,61063,94875,6,1,1
12,0,0,11794,148033,14,1,0
13,0,1,61830,86649,16,1,1
14,0,1,64070,57529,13,1,1
15,0,0,69869,107764,29,0,1
16,1,0,24987,34551,29,0,0
17,1,1,39476,57194,25,0,1
18,1,0,97957,59269,6,0,1
19,0,2,10987,126953,30,1,0
20,1,2,88636,147222,26,0,1
21,1,0,14310,29106,7,1,0
22,1,0,78969,155342,14,0,1
23,0,2,92040,50495,12,1,1
24,0,0,38239,28495,30,0,1
25,0,0,31417,124606,27,1,1
26,1,0,55299,169128,15,0,1
27,1,2,87778,28542,12,1,1
28,1,2,10379,128766,5,1,0
29,1,0,94033,41863,30,1,1
30,1,0,73854,117788,0,1,1
31,0,0,64007,147414,21,0,1
32,1,1,97200,51911,23,0,1
33,1,2,82071,157251,21,0,1
34,1,0,12514,183767,1,1,0
35,1,1,31336,41117,30,1,1
36,1,1,10163,193995,5,1,0
37,0,1,68513,66912,5,1,1
38,0,2,14912,177575,3,0,0
39,0,1,74010,54981,16,1,1
40,0,2,50777,199697,26,1,1
41,1,1,49436,91524,1,0,1
42,0,2,96485,51666,12,0,1
43,1,0,70339,50020,10,0,1
44,1,0,33614,98880,22,0,1
45,1,1,81079,183095,14,1,1
46,1,1,31532,137346,27,1,1
47,1,2,44034,34964,2,0,1
48,0,1,16264,35480,12,0,0
49,0,0,45706,160195,15,1,1
50,1,2,79616,145804,3,1,1
51,1,2,40137,174042,30,0,1
52,0,2,97703,91828,23,0,1
53,1,2,21917,139143,7,1,0
54,0,0,81939,98207,23,0,1
55,1,2,19925,89965,16,1,0
56,0,1,34703,69832,25,1,1
57,0,2,78573,70744,13,0,1
58,1,2,10870,158047,15,0,0
59,0,2,65065,102228,11,0,1
60,1,1,94418,91138,23,0,1
61,1,1,26972,86169,8,0,0
62,0,0,91684,147684,13,1,1
63,1,0,51685,95831,9,0,1
64,1,2,62158,118261,15,0,1
65,0,0,58312,194738,29,0,1
66,1,1,42507,66985,12,1,1
67,1,1,61486,173986,24,0,1
68,0,2,10150,139642,5,0,0
69,1,2,99619,86896,29,0,1
70,1,0,89302,80904,3,1,1
71,0,2,94287,105680,22,0,1
72,1,0,41344,108300,27,1,1
73,1,2,41382,174789,2,1,1
74,0,0,32434,182319,17,0,1
75,0,1,61105,50404,19,1,1
76,1,1,67628,129164,11,0,1
77,1,1,31458,118344,26,0,1
78,1,0,73411,143153,0,0,1
79,0,0,10329,140885,7,1,0
80,0,1,44947,28184,26,0,1
81,1,0,35610,121608,24,0,1
82,0,0,66564,111068,26,1,1
83,0,0,87348,73963,18,1,1
84,0,1,69098,178083,4,1,1
85,1,0,28449,125155,12,1,0
86,1,0,39277,97520,29,1,1
87,1,2,13747,64075,23,0,0
88,0,1,86652,63896,24,1,1
89,1,1,26741,176050,20,0,0
90,0,0,77634,101232,29,0,1
91,1,1,99325,73733,10,1,1
92,0,0,85651,114621,13,0,1
93,1,1,15296,137676,3,1,0
94,0,2,10348,122705,6,1,0
95,1,2,41395,121498,28,1,1
96,0,2,22258,63622,17,0,0
97,1,0,79583,37849,19,1,1
98,1,1,22187,77053,18,1,0
99,0,1,52495,114350,12,0,1
100,1,2,93078,46444,25,0,1
101,1,1,35072,50490,20,1,1
102,1,0,32662,91488,23,0,1
103,0,0,89250,76318,5,1,1
104,0,2,41641,174423,14,0,1
105,0,2,55873,46893,15,0,1
106,1,2,19169,58535,20,1,0
107,0,1,46629,52424,6,1,1
108,1,1,51927,120894,10,1,1
109,1,1,69224,178585,8,1,1
110,0,2,24557,32450,19,1,0
111,0,2,77762,164526,11,1,1
112,1,2,96355,193038,26,1,1
113,1,1,90910,100347,7,1,1
114,0,2,21945,197934,7,0,0
115,1,0,79357,78251,21,1,1
116,0,1,42784,132570,12,0,1
117,0,2,54638,96370,29,1,1
118,0,0,29944,199174,10,0,0
119,0,0,97318,47202,30,1,1
120,1,2,52022,135886,11,1,1
121,1,1,20391,86648,16,1,0
122,1,1,21016,140762,26,0,0
123,1,1,26679,79683,26,0,0
124,1,0,70682,139324,13,0,1
125,1,0,87326,155669,11,0,1
126,1,0,15853,195022,3,1,0
127,0,2,75501,93035,28,1,1
128,0,1,97984,100897,27,1,1
129,1,2,53378,65469,26,0,1
130,1,2,93458,87730,7,1,1
131,1,2,56501,174321,16,1,1
132,0,0,46955,67820,12,0,1
133,0,2,33492,86646,14,1,1
134,1,1,35832,190365,28,0,1
135,1,0,12470,75323,19,1,0
136,0,0,53981,53513,9,0,1
137,1,2,22773,115884,6,0,0
138,0,2,84691,155335,25,0,1
139,1,0,50087,86904,20,0,1
140,1,1,27877,93390,4,1,0
141,1,1,56647,194364,23,1,1
142,0,2,59419,122654,26,1,1
143,1,2,26783,154013,11,0,0
144,1,2,79453,156503,29,1,1
145,0,0,33962,197422,2,1,1
146,0,0,84429,57931,28,1,1
147,1,0,63057,163252,28,0,1
148,0,1,43128,197038,21,0,1
149,0,2,40220,49505,25,0,1
150,0,1,79700,161759,28,0,1
151,0,2,67083,109110,10,0,1
152,0,2,22054,91889,16,0,0
153,1,0,18192,114841,28,0,0
154,0,2,25222,82520,29,1,0
155,1,2,58635,139624,7,0,1
156,1,1,39114,125987,3,1,1
157,1,1,48738,115631,5,0,1
158,0,0,28496,163347,11,0,0
159,1,2,62209,28504,1,0,1
160,1,0,87677,79972,0,1,1
161,1,1,93659,185596,30,1,1
162,1,1,56503,177468,21,1,1
163,1,0,27081,91851,15,1,0
164,1,2,48779,153192,28,0,1
165,1,1,91304,38463,23,1,1
166,0,1,49520,73466,22,1,1
167,0,1,41117,194381,25,0,1
168,0,0,18199,167629,30,0,0
169,1,2,76992,76933,6,1,1
170,0,0,98588,143402,10,0,1
171,1,1,20719,103614,24,0,0
172,0,1,13068,52819,23,1,0
173,1,2,84835,105110,16,1,1
174,1,2,44795,149857,8,0,1
175,1,2,39052,57055,13,0,1
176,0,1,38704,75169,28,0,1
177,0,1,98416,31156,13,1,1
178,0,2,86958,85832,15,1,1
179,1,1,29222,192451,22,1,0
180,1,2,71357,149101,19,0,1
181,0,0,29543,36116,20,0,0
182,0,0,23855,89632,4,1,0
183,0,2,84836,39523,30,1,1
184,0,0,93307,70138,15,1,1
185,0,1,64614,92975,0,1,1
186,0,1,72949,166976,19,1,1
187,0,2,79211,59558,5,1,1
188,0,0,28707,137569,10,0,0
189,1,1,83229,189301,11,1,1
190,0,2,73620,90459,19,0,1
191,0,2,70819,176341,7,1,1
192,1,1,48313,126556,10,1,1
193,1,1,37481,198213,25,0,1
194,1,2,20851,103981,28,0,0
195,1,2,86079,181370,13,1,1
196,1,1,10933,28410,21,0,0
197,0,2,66905,98056,4,1,1
198,0,2,36890,48025,28,1,1
199,1,1,19060,145744,9,1,0
200,1,2,61906,162777,17,1,1
201,1,0,31088,58225,27,1,1
202,1,2,70365,28661,0,1,1
203,1,0,56536,117260,4,0,1
204,0,1,16992,173091,14,0,0
205,0,1,14300,131906,20,1,0
206,1,2,51914,52227,16,1,1
207,1,1,12083,138108,28,0,0
208,1,2,71376,141502,3,0,1
209,1,2,99307,186239,25,1,1
210,1,2,35200,125993,13,1,1
211,1,1,70812,57194,8,1,1
212,1,0,62067,112659,14,0,1
213,1,2,62365,107069,13,0,1
214,0,0,80618,140159,16,0,1
215,0,0,52891,28576,22,0,1
216,0,0,31409,85128,22,0,1
217,1,0,81790,179220,19,1,1
218,0,1,57794,38091,19,0,1
219,1,0,20604,26814,9,0,0
220,1,0,83459,115168,30,0,1
221,1,2,43051,134135,14,0,1
222,1,0,68911,168248,27,0,1
223,1,1,38374,192297,17,1,1
224,0,1,86784,55717,25,1,1
225,1,2,42488,125883,0,1,1
226,0,2,35922,77719,28,0,1
227,1,2,46610,182921,17,1,1
228,0,1,28764,100696,9,1,0
229,0,1,75170,35780,10,0,1
230,0,1,24370,81593,14,1,0
231,1,2,84083,153147,2,0,1
232,1,1,11784,150349,2,0,0
233,0,1,10003,63701,19,1,0
234,0,2,98970,102498,14,0,1
235,0,0,77735,87541,9,0,1
236,1,1,46070,193193,3,0,1
237,0,1,27143,128996,3,1,0
238,1,2,56974,72968,9,1,1
239,0,0,99109,76145,26,0,1
240,0,2,32603,139146,30,1,1
241,1,2,24215,31377,18,1,0
242,0,0,33092,84368,2,1,1
243,0,0,71297,181549,10,1,1
244,1,2,68268,154647,27,0,1
245,0,2,33810,183221,24,0,1
246,1,2,49995,38139,25,0,1
247,1,0,11865,108245,1,0,0
248,0,2,28904,105374,17,1,0
249,1,2,39144,35376,0,1,1
250,0,1,31591,156973,16,0,1
251,1,2,30167,173228,7,0,1
252,0,2,72382,40855,28,1,1
253,1,2,79869,77256,29,0,1
254,0,0,70526,193263,26,0,1
255,1,1,38143,170030,8,0,1
256,1,1,70298,168568,14,0,1
257,1,1,54747,31611,17,1,1
258,0,0,92997,74119,28,1,1
259,0,1,24347,197841,7,0,0
260,1,2,57445,92333,28,0,1
261,0,2,70645,68788,7,1,1
262,0,0,69540,120415,21,0,1
263,1,1,70712,69386,21,1,1
264,0,2,32900,118899,5,0,1
265,0,1,14326,101996,4,1,0
266,1,1,43865,173276,17,1,1
267,0,2,29046,183946,11,0,0
268,0,2,95088,98378,3,1,1
269,1,1,38586,125450,13,1,1
270,0,1,30468,130680,5,0,1
271,0,2,42254,183682,20,0,1
272,0,2,32467,126488,1,1,1
273,1,0,68404,58942,20,0,1
274,1,1,58451,112584,25,0,1
275,1,1,86208,55591,0,1,1
276,0,2,62426,44251,17,1,1
277,0,0,63710,117364,11,0,1
278,0,1,25062,114823,11,0,0
279,1,2,56438,74136,12,1,1
280,0,0,17783,33184,1,0,0
281,0,2,92426,167403,7,1,1
282,1,1,64667,59590,29,0,1
283,1,0,32483,129276,22,0,1
284,0,0,15673,188383,22,1,0
285,0,2,77511,63420,10,0,1
286,1,0,76182,113724,6,0,1
287,1,2,89831,77102,1,1,1
288,1,1,12072,174196,21,1,0
289,0,2,81231,196816,14,0,1
290,1,1,48169,193003,30,1,1
291,1,2,31699,62475,26,1,1
292,1,2,15710,76406,1,1,0
293,0,0,31645,43899,21,1,1
294,1,2,98933,74074,2,0,1
295,1,1,52912,40089,10,0,1
296,1,0,68756,167600,26,0,1
297,0,1,41087,36924,15,0,1
298,0,2,46798,119904,21,1,1
299,1,2,34475,197916,7,0,1
300,0,1,98334,74052,30,0,1
301,1,1,10900,39797,11,0,0
302,1,0,61445,97109,27,0,1
303,1,0,78796,189061,13,1,1
304,1,0,62141,106757,23,1,1
305,0,2,90945,161265,29,1,1
306,1,0,88918,185099,12,0,1
307,0,0,62873,31819,25,0,1
308,1,1,70949,183445,30,0,1
309,1,2,31521,123761,20,1,1
310,1,0,59615,189435,22,1,1
311,0,1,52111,50013,19,0,1
312,1,2,34598,31641,18,0,1
313,1,2,61124,124848,2,0,1
314,0,2,59689,85255,4,0,1
315,1,0,23075,176278,19,0,0
316,0,1,48192,70323,25,0,1
317,1,1,77367,116745,23,0,1
318,0,0,82625,121324,14,1,1
319,1,0,51802,153308,24,1,1
320,1,2,78922,78897,11,1,1
321,0,2,38670,84215,6,1,1
322,0,0,48392,160932,24,1,1
323,1,1,47425,165175,13,0,1
324,1,2,73906,171288,15,0,1
325,0,2,94013,25779,16,1,1
326,1,0,27698,165001,19,1,0
327,1,1,26793,162777,7,0,0
328,0,0,67033,93414,12,1,1
329,0,2,20109,39360,10,0,0
330,0,1,95185,43176,29,0,1
331,1,1,27684,60999,15,1,0
332,1,0,98240,84132,1,0,1
333,1,2,18032,44775,13,1,0
334,0,2,46470,118274,13,1,1
335,1,1,33301,140998,15,0,1
336,0,1,62800,73146,5,0,1
337,1,1,27520,73490,7,0,0
338,1,0,26094,111264,23,0,0
339,1,2,13571,110940,10,0,0
340,1,1,36239,54437,21,1,1
341,0,1,77082,83900,8,1,1
342,1,1,71572,31097,7,1,1
343,1,0,30495,161143,17,0,1
344,0,1,49771,192313,5,1,1
345,1,0,32905,118798,6,0,1
346,0,2,21337,134635,30,1,0
347,0,1,16082,80991,0,1,0
348,1,2,43883,42269,2,0,1
349,1,0,15491,72255,30,1,0
350,0,1,48081,89949,25,0,1
351,1,1,36317,114922,12,0,1
352,0,0,15627,72115,16,1,0
353,1,1,51028,141622,29,0,1
354,1,1,14422,176891,27,1,0
355,1,2,45525,56488,17,0,1
356,0,1,23480,46480,27,0,0
357,0,1,19184,84034,28,0,0
358,1,2,80239,96432,24,1,1
359,1,2,33215,157299,11,0,1
360,1,2,65203,107937,5,1,1
361,1,0,65190,62671,20,0,1
362,1,0,16320,75552,17,1,0
363,1,2,21696,52584,7,1,0
364,1,1,56129,62943,17,0,1
365,0,0,74971,134321,10,1,1
366,1,1,33356,131469,30,0,1
367,1,1,29607,95404,24,1,0
368,1,0,95319,128428,14,0,1
369,0,1,94413,89122,28,0,1
370,0,0,78963,86119,5,1,1
371,1,2,66865,75580,5,0,1
372,1,1,40427,168473,9,0,1
373,0,1,93733,175719,21,1,1
374,1,0,63543,147614,9,1,1
375,0,1,41184,130935,2,0,1
376,0,0,96652,188067,26,0,1
377,1,2,56555,103490,30,0,1
378,1,0,36457,152471,6,0,1
379,0,2,26101,112774,13,0,0
380,1,1,36156,197699,2,0,1
381,0,2,49958,61920,4,0,1
382,1,0,68696,139269,29,0,1
383,1,1,97453,148246,5,1,1
384,1,1,68533,147346,25,0,1
385,0,2,96438,140132,27,0,1
386,0,2,50348,140642,27,1,1
387,1,2,85016,56597,9,1,1
388,1,0,73188,151636,4,1,1
389,1,2,64225,183187,5,1,1
390,1,2,64437,57324,17,0,1
391,0,1,66330,29934,1,0,1
392,1,0,26372,37776,15,0,0
393,0,1,30714,68687,30,1,1
394,0,0,84263,64990,21,1,1
395,1,2,86531,183094,5,0,1
396,1,2,93090,176330,21,0,1
397,0,1,79373,91689,14,1,1
398,0,1,17440,64070,2,1,0
399,0,2,81536,74497,21,0,1
400,1,1,62494,197421,16,0,1
401,0,1,37580,73065,20,0,1
402,1,0,60822,105376,11,0,1
403,0,0,96032,130912,27,1,1
404,1,0,91545,34334,21,1,1
405,0,0,73313,140266,28,0,1
406,0,1,54345,107688,2,0,1
407,0,2,33138,52144,6,0,1
408,1,0,33579,77059,22,0,1
409,0,2,83094,163058,1,0,1
410,0,0,90065,41152,27,0,1
411,0,1,51913,46253,19,0,1
412,1,2,81378,28446,11,0,1
413,1,2,32236,112890,11,1,1
414,0,0,97980,27300,1,1,1
415,0,0,38626,131493,21,0,1
416,0,2,64230,33982,30,0,1
417,0,0,38183,76625,2,0,1
418,1,0,89277,104183,18,0,1
419,0,1,68269,138074,20,0,1
420,0,0,58751,84473,2,0,1
421,1,2,88720,135185,13,0,1
422,0,0,99311,191983,14,1,1
423,0,1,94528,80249,19,1,1
424,1,1,72268,94199,0,1,1
425,1,0,79593,121506,27,0,1
426,1,0,94247,50373,25,1,1
427,0,0,76700,99025,10,0,1
428,1,1,12011,128266,24,1,0
429,0,2,87935,153748,30,1,1
430,1,1,98720,161215,8,0,1
431,0,2,38638,168360,25,1,1
432,0,1,37857,157217,11,1,1
433,0,1,15532,129265,14,1,0
434,1,2,22159,87188,19,1,0
435,0,0,91547,111774,4,1,1
436,0,0,98738,158057,4,1,1
437,1,1,21966,117250,20,1,0
438,0,2,14398,74697,14,0,0
439,1,0,18572,48956,8,0,0
440,0,2,77312,170407,13,1,1
441,0,0,42074,70314,24,0,1
442,1,2,82799,193775,27,0,1
443,1,2,12659,189209,9,0,0
444,1,2,19649,36956,14,0,0
445,0,0,50119,128451,12,0,1
446,0,2,18888,65708,28,0,0
447,0,1,83061,166606,5,1,1
448,1,2,39343,114597,28,1,1
449,0,1,92007,27875,11,0,1
450,1,0,78728,91936,8,1,1
451,1,0,48640,108262,10,1,1
452,0,2,92070,42620,10,0,1
453,1,2,97341,41504,26,0,1
454,0,1,97493,29602,15,1,1
455,0,1,78400,65533,23,1,1
456,0,2,52862,53788,23,1,1
457,0,1,11804,36055,24,1,0
458,1,2,10455,110892,18,1,0
459,1,0,25766,125407,21,0,0
460,0,0,58199,54701,10,1,1
461,0,2,88613,163901,6,1,1
462,0,0,16690,149327,17,0,0
463,0,0,71164,40460,3,1,1
464,0,1,48825,143349,16,1,1
465,0,0,29236,116282,21,0,0
466,0,1,59689,186013,16,0,1
467,1,0,48940,106946,20,1,1
468,1,0,64320,38814,18,1,1
469,1,2,84845,65487,13,1,1
470,1,1,52663,148686,26,0,1
471,0,2,17957,192410,21,1,0
472,0,1,69018,151963,11,1,1
473,1,2,58496,147367,16,1,1
474,1,0,99128,80729,0,0,1
475,0,2,35868,36081,12,1,1
476,0,2,79478,183057,7,1,1
477,1,0,57402,158849,29,0,1
478,0,0,73795,65242,6,0,1
479,1,1,58403,68995,21,0,1
480,0,0,85972,72252,26,1,1
481,1,2,62998,120012,13,0,1
482,0,2,32786,125771,12,0,1
483,0,2,17962,100961,10,0,0
484,1,1,59440,114646,28,1,1
485,0,2,94772,52766,23,0,1
486,1,2,80083,57230,29,1,1
487,1,2,81026,83402,13,1,1
488,1,2,86883,76718,10,1,1
489,1,1,39444,148821,6,0,1
490,0,1,35886,120996,24,0,1
491,0,0,24541,82029,10,0,0
492,1,2,54502,98123,18,1,1
493,0,1,17183,103226,29,0,0
494,0,2,39562,197045,13,1,1
495,0,1,70157,59156,24,0,1
496,1,0,72151,59382,5,1,1
497,0,2,65170,100331,3,0,1
498,1,2,67936,164924,24,1,1
499,1,2,93339,48744,2,1,1
500,1,2,57365,158780,11,1,1
501,0,0,56628,55842,4,1,1
502,0,1,83814,53240,1,1,1
503,1,1,75324,81550,17,1,1
504,0,0,46939,198571,19,1,1
505,0,0,71428,74910,15,1,1
506,0,2,23884,111105,8,1,0
507,1,2,95145,101272,24,1,1
508,0,2,46002,195357,19,0,1
509,0,1,20309,65531,27,1,0
510,1,1,72115,75436,14,1,1
511,0,1,42769,153233,5,1,1
512,1,2,91870,137948,22,1,1
513,0,0,55308,140400,10,0,1
514,0,0,60789,31380,6,0,1
515,0,0,51363,87868,13,0,1
516,1,2,99239,76337,18,1,1
517,0,2,19272,195078,26,0,0
518,1,2,44411,112591,26,1,1
519,1,2,60915,162102,25,1,1
520,0,0,98433,142426,8,1,1
521,0,0,81867,51104,15,0,1
522,0,0,43980,103343,10,0,1
523,0,0,50286,42198,12,0,1
524,1,1,29385,164391,27,0,0
525,1,2,47565,75307,23,0,1
526,0,0,26494,82565,12,0,0
527,0,1,59243,180274,27,0,1
528,0,1,91488,172612,10,0,1
529,0,0,33116,83388,14,0,1
530,1,0,93364,194421,17,1,1
531,1,1,70743,124440,14,1,1
532,1,0,34007,98662,16,0,1
533,0,0,26128,54113,19,1,0
534,1,1,33748,91567,13,1,1
535,0,1,38896,189851,3,0,1
536,0,2,40674,157025,14,0,1
537,1,2,97111,100651,6,0,1
538,0,1,54850,119976,12,0,1
539,1,0,32948,57390,8,0,1
540,1,2,12682,110308,22,0,0
541,1,0,12453,191874,30,1,0
542,1,1,34655,199778,27,0,1
543,0,2,59351,130816,13,0,1
544,0,2,29916,133877,21,1,0
545,1,0,36532,109079,8,0,1
546,0,1,94583,59091,6,0,1
547,1,2,92819,42690,25,1,1
548,1,0,76535,154393,9,1,1
549,0,1,91220,74058,11,1,1
550,0,1,71238,68160,2,1,1
551,1,1,32356,123082,0,1,1
552,0,2,89094,109191,5,1,1
553,0,2,91462,26884,13,1,1
554,0,0,75585,147788,27,0,1
555,0,2,31629,53848,10,0,1
556,0,2,42063,34242,12,0,1
557,1,1,12810,157421,10,0,0
558,0,0,85570,191139,12,1,1
559,1,0,72026,180424,26,0,1
560,0,0,90444,182562,24,0,1
561,0,1,50403,36861,29,1,1
562,1,0,78867,100064,12,0,1
563,1,1,95920,116495,6,1,1
564,1,1,41545,30098,11,1,1
565,0,0,63912,31064,28,0,1
566,0,1,92498,33460,28,0,1
567,1,2,16316,129912,30,0,0
568,0,2,68617,150036,22,1,1
569,1,2,59860,38074,12,1,1
570,0,2,55981,161629,29,1,1
571,0,2,34833,95421,7,1,1
572,1,1,39818,148068,13,0,1
573,1,1,59227,116161,20,0,1
574,1,0,44809,28768,29,1,1
575,0,0,10735,95975,13,1,0
576,1,1,50242,79653,15,1,1
577,1,1,56166,52940,5,1,1
578,0,0,42483,185339,6,0,1
579,1,2,70572,125112,7,1,1
580,1,0,31721,123335,1,1,1
581,1,0,31085,57473,10,1,1
582,1,1,84931,32907,12,1,1
583,0,1,69036,28874,19,0,1
584,0,0,42679,155684,4,1,1
585,0,2,84557,137622,2,1,1
586,1,2,54126,106230,30,0,1
587,0,2,87685,154677,26,1,1
588,1,1,85076,93242,27,1,1
589,1,1,31633,30774,10,0,1
590,0,1,43018,85195,14,1,1
591,1,2,27394,132859,18,1,0
592,1,2,68152,75143,16,0,1
593,0,0,84775,131963,10,1,1
594,0,1,47364,97526,9,1,1
595,1,0,76340,39492,7,1,1
596,1,0,69967,55369,2,1,1
597,0,0,47334,154058,0,1,1
598,1,1,98592,180083,17,0,1
599,0,0,96519,158137,16,0,1

In [194]:
# splitting the data into training and testing data set
x_train, x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=1)

In [195]:
# building the model
model = DecisionTreeClassifier(criterion = 'entropy',max_depth=3)
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [196]:
# predicting the data
y.preds = model.predict(x_test) # predicting on test data set 
pd.Series(y.preds).value_counts() # getting the count of each category

1    120
dtype: int64

In [197]:
y.preds

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [198]:
pd.crosstab(y_test,y.preds)

col_0           1
Taxable.Risky
0              23
1              97

In [201]:
# finding out athe accuracy of the model
np.mean(y.preds==y_test)*100

80.83333333333333